# Generated by Django 5.2.8 on 2025-12-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='Pedido',
            new_name='pedido',
        ),
    ]
