# Generated by Django 5.2.8 on 2025-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_pedido_detallepedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='No especificado', max_length=50),
        ),
    ]
