# Generated by Django 5.2.8 on 2025-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pedido_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
