# Generated by Django 5.2.8 on 2025-12-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='visto_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
